FORMAT: 1A
HOST: https://bath-climate.herokuapp.com/bathclimate

# bathclimate

bathclimate is a simple API allowing consumers to change bath climate.

## Test [/]

### Test Request [GET]

+ Response 200 (application/json)

        {
            "test": "bathclimate"

        }