FORMAT: 1A
HOST: https://bath-climate.herokuapp.com/webapi

# bathclimate

bathclimate is a simple API allowing consumers to change bath climate.

## Ping  [/ping]

### Ping service [GET]

allows customers to see if service is running

+ Response 200 (application/json)

        {
            "test": "bathclimate"

        }
 
 
## Get humidity collection [GET/houses/{house_id}/humidity?count={count}&order={order}]

Returns a current humidity value in bath.
ex: GET/houses/1/humidity?count=10&order=desc

+ Parameters
    + house_id  (number) - ID of house
    + count     (number) - quantity of records
    + order     (string) - increase or decrease order

    
+ response 200 (application/json)
    + Body
            
            {
                "measurements": [
                                    {
                                        "humidity": 50.12,
                                        "measurement_time": "2016-06-11T14:25:43.122Z"
                                    },
                                    {
                                        "humidity": 54.16,
                                        "measurement_time": "2016-06-11T14:24:41.432Z"
                                    },
                                    {
                                        "humidity": 63.52,
                                        "measurement_time": "2016-06-11T14:23:41.223Z"
                                    }
                                ]
            }

+ Response 409 (application/json)
    + Body
            
            {
                "max_measurements": 100
            }

        
## Is light turn on [GET/house/{house_id}/light]

Returns 204 if light is turn on in bath, 404 - otherwise.

+ Parameters
    + house_id (number) - ID of house
    
+ Response 204 
+ Response 404


## Light sensors collection [GET/light_sensors_states]

Returns all light sensor state from every house.

+ Response 200 (applicaion/json)
    + Body
    
            {   
                "houses":
                    [   
                        {
                            "house_id": "1",
                            "is_light_on": "true"
                        },
                        {
                            "house_id": "2",
                            "is_light_on": "false"
                        },
                        {
                            "house_id": "3",
                            "is_light_on": "true"
                        }    
                    ]
            }


## Is ventilation turn on [GET/houses/{house_id}/vent]

Returns status 200 if ventilation is turn on in bath, 404 - otherwise.

+ Parameters
    + house_id      (number) - ID of house

+ Response 204
+ Response 404


## Turn on ventilation [PUT/houses/{house_id}/vent]

Turns on ventilation if it is off.

+ Parameters
    + house_id  (number)  - ID of house

+ Response 200

+ Response 404


## Turn off ventilation [DELETE/houses/{house_id}/vent]

Turns off ventilation if it is on.

+ Parameters
    + house_id  (number)  - ID of house
    
+ Response 200